### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by brunolemos** [devhubapp/devhub#126]
- [x] App get super slow after being opened for a long period of time
- [x] Android animations are too slow (https://github.com/react-spring/react-spring/issues/570)
  - [x] Temporarily disable animations on android for performance reasons (https://github.com/devhubapp/devhub/commit/4a8f6574c52eaac0525e0ca2a1f120e43266cbfb)
  - [x] Fix it for real (kinda)
  - [x] Re-enable animations on Android
- [ ] Move all remaining static styles to `StyleSheet.create()` (https://github.com/necolas/react-native-web/issues/1136#issuecomment-470203321)
- [x] Use react-spring on just a couple components, not on everything like I'm currently doing due to theme change (https://github.com/react-spring/react-spring/issues/570#issuecomment-466831741)
- [x] Optimize a couple redux selectors that are triggering unnecessary re-renders 
- [ ] Use GraphQL to fetch notification enhancements instead of doing dozens of api requests 
- [ ] Extract static CSS if possible
- [ ] Use something faster than redux-persist+localstorage (maybe [kv-storage](https://twitter.com/philwalton/status/1105339460013613057?s=20)? sqlite? [watermelondb](https://github.com/Nozbe/WatermelonDB)?)
- [x] Disable buggy `FlatList` virtualization on web (https://github.com/necolas/react-native-web/issues/1337)
- [ ] Maybe use something like [react-window](https://github.com/bvaughn/react-window)?
- [x] Investigate other performance issues

**Comment by MSF-Jarvis** [comment]
Despite the fixes referenced here, the animation of opening settings is still unbearably slow and laggy even on high-end Android devices :(

**Comment by brunolemos** [comment]
@MSF-Jarvis yeah, I can disabled animations on android again. But for performance I think only after https://github.com/react-spring/react-spring/issues/299 and https://github.com/react-spring/react-spring/issues/570.

**Comment by MSF-Jarvis** [comment]
I'd rather have no animations than terrible ones but that's a personal opinion probably not shared by others.

**Comment by brunolemos** [comment]
I was able to fix the animation performance, it will be available in the next version.

**Comment by brunolemos** [comment]
@msf-jarvis can you please upgrade to v0.91+ and let me know if android feels faster?

**Comment by MSF-Jarvis** [comment]
> @MSF-Jarvis can you please upgrade to v0.91+ and let me know if android feels faster?

Did a few hours ago, it's perfect!

**Comment by chylex** [comment]
Just installed 0.92 on Android 9 and it feels fairly unresponsive, if I tap one of the bottom buttons to switch columns, it takes usually 2-3 seconds to switch; on top of that, sometimes after a fresh start, I can switch to another column and nothing happens even after waiting for 15+ seconds, I have to tap multiple times and it switches eventually.

Animations themselves seem smooth, it feels more like the app is waiting for a network response with no loading animation or other indication that it's at least doing something, just a guess though.

**Comment by brunolemos** [comment]
@chylex thanks for reporting. If you have experience with react, some help is highly appreciated.
