### ISSUE TITLE
More filters

### ISSUE THREAD

**Issue by brunolemos** [devhubapp/devhub#131]
## Existing filters
- Filter by participating notifications
- Filter by saved for later status
- Filter by read status
- Filter by notification reason (mentioned, commented, etc)
- Filter by event type (starred, pushed, etc)
- Filter by privacy
- Filter by subject type (issue, pr, commit, etc)
- Filter by issue/pr state (open, closed, merged, draft)

### Recently added

- [x] Filter by owner/repo 
- [x] Filter by "involved user" (https://github.com/devhubapp/devhub/pull/145)
- [x] Filter by text (#149)
- [x] Filter bots (#20)

## More filters
- [x] Filter by labels _(already works since #149 but has no UI yet, only the search bar)_
- [x] Filter by usernames
- [ ] Filter by assignment (#14)
- [x] Filter by review requested (#14)
